🎯 COMPLETE AI STRATEGY ADVISOR - COPY EACH SECTION EXACTLY

=== FILE 1: package.json ===
{
  "name": "ai-strategy-advisor",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "lucide-react": "^0.263.1"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react": "^4.0.3",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "postcss": "^8.4.27",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  }
}

=== FILE 2: index.html ===
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="AI Strategy Advisor - Interactive tool for AI adoption strategies" />
    <title>AI Strategy Advisor</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>

=== FILE 3: vite.config.ts ===
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  base: '/ai-strategy-advisor/',
})

=== FILE 4: tailwind.config.js ===
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

=== FILE 5: src/main.tsx ===
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)

=== FILE 6: src/index.css ===
@tailwind base;
@tailwind components;
@tailwind utilities;

=== FILE 7: .github/workflows/deploy.yml ===
name: Deploy AI Strategy Advisor

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

=== FILE 8: README.md ===
# AI Strategy Advisor

🎯 Interactive tool for AI strategy assessment and implementation planning.

## 🚀 Live Demo
**[https://himjoe.github.io/ai-strategy-advisor](https://himjoe.github.io/ai-strategy-advisor)**

## 🌟 Features
- 8-step strategic assessment process
- Dynamic strategy canvas generation
- Industry-specific recommendations
- Risk management framework

## 🛠 Tech Stack
- React + TypeScript
- Vite + Tailwind CSS
- GitHub Pages deployment

Built with ❤️ by HimJoe
